# Etapa 1: Construcción
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build-env
WORKDIR /app

# Copiar archivos de proyecto y restaurar dependencias
COPY *.csproj ./
RUN dotnet restore

# Copiar el resto del código y compilar
COPY . ./
RUN dotnet publish -c Release -o out

# Etapa 2: Imagen de producción
FROM mcr.microsoft.com/dotnet/aspnet:9.0
WORKDIR /app

# Copiar el resultado de la compilación desde la etapa anterior
COPY --from=build-env /app/out ./

# Nombre del archivo DLL generado (asegúrate que sea el correcto)
ENV APP_NET_CORE=Prueba_Geolocalizacion.dll

# Puerto expuesto por la app (puedes ajustar si usas otro)
ENV ASPNETCORE_URLS=http://+:8080
EXPOSE 808
